
/* Generated File. DO NOT EDIT. */
/*
 * List of extensions and their types.
 */

#ifndef __EXT_H__
#define __EXT_H__
struct ext_entry {
	char *ext;
	int type;
	int len;
} extlist[] = {
	{"c"	, TYPE_TEXT, 1},
	{"h"	, TYPE_TEXT, 1},
	{"cc"	, TYPE_TEXT, 2},
	{"cpp"	, TYPE_TEXT, 3},
	{"c++"	, TYPE_TEXT, 3},
	{"hpp"	, TYPE_TEXT, 3},
	{"txt"	, TYPE_TEXT, 3},
	{"html"	, TYPE_TEXT, 4},
	{"htm"	, TYPE_TEXT, 3},
	{"xml"	, TYPE_TEXT, 3},
	{"info"	, TYPE_TEXT, 4},
	{"ppm"	, TYPE_TEXT, 3},
	{"svg"	, TYPE_TEXT, 3},
	{"conf"	, TYPE_TEXT, 4},
	{"py"	, TYPE_TEXT, 2},
	{"rb"	, TYPE_TEXT, 2},
	{"xpm"	, TYPE_TEXT, 3},
	{"js"	, TYPE_TEXT, 2},
	{"jsp"	, TYPE_TEXT, 3},
	{"pl"	, TYPE_TEXT, 2},
	{"tcl"	, TYPE_TEXT, 3},
	{"sh"	, TYPE_TEXT, 2},
	{"php"	, TYPE_TEXT, 3},
	{"bat"	, TYPE_TEXT, 3},
	{"pm"	, TYPE_TEXT, 2},
	{"r"	, TYPE_TEXT, 1},
	{"d"	, TYPE_TEXT, 1},
	{"bas"	, TYPE_TEXT, 3},
	{"asm"	, TYPE_TEXT, 3},
	{"go"	, TYPE_TEXT, 2},
	{"java"	, TYPE_TEXT, 4},
	{"m4"	, TYPE_TEXT, 2},
	{"vb"	, TYPE_TEXT, 2},
	{"xslt"	, TYPE_TEXT, 4},
	{"yacc"	, TYPE_TEXT, 4},
	{"lex"	, TYPE_TEXT, 3},
	{"csv"	, TYPE_TEXT, 3},
	{"shtml"	, TYPE_TEXT, 5},
	{"xhtml"	, TYPE_TEXT, 5},
	{"xht"	, TYPE_TEXT, 3},
	{"asp"	, TYPE_TEXT, 3},
	{"aspx"	, TYPE_TEXT, 4},
	{"rss"	, TYPE_TEXT, 3},
	{"atom"	, TYPE_TEXT, 4},
	{"cgi"	, TYPE_TEXT, 3},
	{"c#"	, TYPE_TEXT, 2},
	{"cob"	, TYPE_TEXT, 3},
	{"ada"	, TYPE_TEXT, 3},
	{"ini"	, TYPE_TEXT, 3},
	{"y"	, TYPE_TEXT, 1},
	{"swg"	, TYPE_TEXT, 3},
	{"s"	, TYPE_TEXT, 1},
	{"ps"	, TYPE_TEXT, 2},
	{"bib"	, TYPE_TEXT, 3},
	{"lua"	, TYPE_TEXT, 3},
	{"qml"	, TYPE_TEXT, 3},
	{"exe"	, TYPE_EXE, 3},
	{"dll"	, TYPE_EXE, 3},
	{"bin"	, TYPE_EXE, 3},
	{"o"	, TYPE_EXE, 1},
	{"a"	, TYPE_EXE, 1},
	{"obj"	, TYPE_EXE, 3},
	{"so"	, TYPE_EXE, 2},
	{"com"	, TYPE_EXE, 3},
	{"xpi"	, TYPE_EXE, 3},
	{"off"	, TYPE_EXE, 3},
	{"pdf"	, TYPE_COMPRESSED, 3},
	{"jpg"	, TYPE_JPEG, 3},
	{"jpeg"	, TYPE_JPEG, 4},
	{"png"	, TYPE_COMPRESSED, 3},
	{"mp3"	, TYPE_COMPRESSED, 3},
	{"wma"	, TYPE_COMPRESSED, 3},
	{"divx"	, TYPE_COMPRESSED, 4},
	{"mp4"	, TYPE_COMPRESSED, 3},
	{"aac"	, TYPE_COMPRESSED, 3},
	{"m4a"	, TYPE_COMPRESSED, 3},
	{"m4p"	, TYPE_COMPRESSED, 3},
	{"ofs"	, TYPE_COMPRESSED, 3},
	{"ofr"	, TYPE_COMPRESSED, 3},
	{"flac"	, TYPE_COMPRESSED, 4},
	{"pac"	, TYPE_COMPRESSED, 3},
	{"gif"	, TYPE_COMPRESSED, 3},
	{"jp2"	, TYPE_JPEG, 3},
	{"gz"	, TYPE_COMPRESSED, 2},
	{"bz2"	, TYPE_COMPRESSED, 3},
	{"zip"	, TYPE_COMPRESSED, 3},
	{"arj"	, TYPE_COMPRESSED, 3},
	{"arc"	, TYPE_COMPRESSED, 3},
	{"jar"	, TYPE_COMPRESSED, 3},
	{"lz"	, TYPE_COMPRESSED, 2},
	{"lzh"	, TYPE_COMPRESSED, 3},
	{"lzma"	, TYPE_COMPRESSED, 4},
	{"lzo"	, TYPE_COMPRESSED, 3},
	{"dmg"	, TYPE_COMPRESSED, 3},
	{"7z"	, TYPE_COMPRESSED, 2},
	{"uha"	, TYPE_COMPRESSED, 3},
	{"alz"	, TYPE_COMPRESSED, 3},
	{"ace"	, TYPE_COMPRESSED, 3},
	{"xcf"	, TYPE_BINARY, 3},
};
#define	NUM_EXT	(99)
#endif
